# Imagen base ligera con Python
FROM python:3.11-slim

# Establecer directorio de trabajo
WORKDIR /app

# Copiar requirements si existe (mejor para cacheo)
COPY requirements.txt .

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto del código del backend
COPY ./backend ./backend

# Exponer el puerto donde corre FastAPI
EXPOSE 8000

# Comando para iniciar la aplicación
CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]