### Register User
POST localhost:8000/auth/register
Content-Type: application/json
Accept: application/json

{
  "email": "test@gmail.com",
  "password": "test1234",
  "name": "Test User"
}

### Login User
POST localhost:8000/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "test@gmail.com",
  "password": "test1234"
}

> {%
    client.global.set("token", response.body.access_token)
%}

### Test Authenticated Endpoint
GET localhost:8000/auth/test
Authorization: Bearer {{ token }}
Content-Type: application/json
Accept: application/json

### Send individual message
POST localhost:8000/msg/message/mark.albrand5@gmail.com
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{ token }}

{
  "mensaje": "Hello, this is a test message!",
  "clave_privada_pem": "-----BEGIN PRIVATE KEY-----\nMIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgUz/l3lQZskDz+GqM\naf9dM2UySv9i/rO3YHQ9R3D9wkihRANCAAS8V+opfsE8WjgordHZCNPmuP+VcmU7\nWkCIBM0Qx9Nz5vBTYF2OT4m3oQz4350CvWn6vvVlej0spRrDtSlbp/18\n-----END PRIVATE KEY-----\n"
}

### Get transactions
GET localhost:8000/blockchain/transactions
Authorization: Bearer {{ token }}
Content-Type: application/json
Accept: application/json

### Verify integrity of a transaction
GET localhost:8000/blockchain/transactions/integridad
Authorization: Bearer {{ token }}
Content-Type: application/json
Accept: application/json

### Verify integrity of a transaction for a group
GET localhost:8000/blockchain/transactions/integridad-grupal
Authorization: Bearer {{ token }}
Content-Type: application/json
Accept: application/json

### Clear
POST localhost:8000/dev/clear-db
Content-Type: application/json
Accept: application/json