# Name of your application. Used to uniquely configure containers.
service: cifrados-proyecto-2-frontend

# Name of the container image.
image: markalbrand/cifrados-proyecto-2-frontend

# Deploy to these servers.
servers:
  web:
    - server1.albrand.tech # Use the server's hostname or IP address.

# Enable SSL auto certification via Let's Encrypt (and allow for multiple apps on one server).
proxy:
  ssl: true # Disable Cloudflare Proxy if using SSL=true
  host: cf-frontend.albrand.tech # Hostname for the app
  app_port: 80
  healthcheck:
    interval: 3
    path: /
    timeout: 3

# Credentials for your image host.
registry:
  username: markalbrand

  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64
  context: .
  dockerfile: Dockerfile.frontend

ssh:
  user: deployer # Server user to connect as (default: root)
  keys: ["~/.ssh/hetzner-access"] # List of SSH keys to use for authentication
